### ISSUE TITLE
Q- subscription leakage?

### ISSUE THREAD

**Issue by Tommertom** [nohea/enehana-fgslider#1]
Hi there

https://github.com/nohea/enehana-fgslider/blob/master/src/lib/graphql-ws.js

Isnt there a subscription leakage on client? In function toObservable?

Regards, Tom

**Comment by nohea** [comment]
> Isnt there a subscription leakage on client? In function toObservable?

Not sure - i did add an onDestroy() event handler to unsubscribe() in the page.svelte, but i didn't actually test it. 

Open to feedback 🙂 - i'm not a front-end performance tuner unless forced

**Comment by nohea** [comment]
i think its resolved in d3f687fc90310aecf6dd3d79694c6c6c9847afbe
